/*
 * Copyright 2019 Maksim Zheravin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <cstdint>
#include <exchange/core/common/CoreSymbolSpecification.h>
#include <exchange/core/common/SymbolType.h>

namespace exchange {
namespace core2 {
namespace tests {
namespace util {

struct TestConstants {
  static constexpr int32_t SYMBOL_MARGIN = 5991;
  static constexpr int32_t SYMBOL_EXCHANGE = 9269;
  static constexpr int32_t SYMBOL_EXCHANGE_FEE = 9340;

  static constexpr int64_t UID_1 = 1440001;
  static constexpr int64_t UID_2 = 1440002;
  static constexpr int64_t UID_3 = 1440003;
  static constexpr int64_t UID_4 = 1440004;

  static constexpr int32_t SYMBOL_AUTOGENERATED_RANGE_START = 40000;

  // Currency codes (ISO 4217)
  static constexpr int32_t CURRENCY_AUD = 36;
  static constexpr int32_t CURRENCY_BRL = 986;
  static constexpr int32_t CURRENCY_CAD = 124;
  static constexpr int32_t CURRENCY_CHF = 756;
  static constexpr int32_t CURRENCY_CNY = 156;
  static constexpr int32_t CURRENCY_CZK = 203;
  static constexpr int32_t CURRENCY_DKK = 208;
  static constexpr int32_t CURRENCY_EUR = 978;
  static constexpr int32_t CURRENCY_GBP = 826;
  static constexpr int32_t CURRENCY_HKD = 344;
  static constexpr int32_t CURRENCY_JPY = 392;
  static constexpr int32_t CURRENCY_KRW = 410;
  static constexpr int32_t CURRENCY_MXN = 484;
  static constexpr int32_t CURRENCY_MYR = 458;
  static constexpr int32_t CURRENCY_NOK = 578;
  static constexpr int32_t CURRENCY_NZD = 554;
  static constexpr int32_t CURRENCY_PLN = 985;
  static constexpr int32_t CURRENCY_RUB = 643;
  static constexpr int32_t CURRENCY_SEK = 752;
  static constexpr int32_t CURRENCY_SGD = 702;
  static constexpr int32_t CURRENCY_THB = 764;
  static constexpr int32_t CURRENCY_TRY = 949;
  static constexpr int32_t CURRENCY_UAH = 980;
  static constexpr int32_t CURRENCY_USD = 840;
  static constexpr int32_t CURRENCY_VND = 704;
  static constexpr int32_t CURRENCY_XAG = 961;
  static constexpr int32_t CURRENCY_XAU = 959;
  static constexpr int32_t CURRENCY_ZAR = 710;

  // Cryptocurrencies
  static constexpr int32_t CURRENCY_XBT = 3762; // satoshi, 1E-8
  static constexpr int32_t CURRENCY_ETH = 3928; // szabo, 1E-6
  static constexpr int32_t CURRENCY_LTC = 4141; // litoshi, 1E-8
  static constexpr int32_t CURRENCY_XDG = 4142;
  static constexpr int32_t CURRENCY_GRC = 4143;
  static constexpr int32_t CURRENCY_XPM = 4144;
  static constexpr int32_t CURRENCY_XRP = 4145;
  static constexpr int32_t CURRENCY_DASH = 4146;
  static constexpr int32_t CURRENCY_XMR = 4147;
  static constexpr int32_t CURRENCY_XLM = 4148;
  static constexpr int32_t CURRENCY_ETC = 4149;
  static constexpr int32_t CURRENCY_ZEC = 4150;

  // Create SYMBOLSPEC_EUR_USD
  static exchange::core::common::CoreSymbolSpecification
  CreateSymbolSpecEurUsd();

  // Create SYMBOLSPECFEE_USD_JPY
  static exchange::core::common::CoreSymbolSpecification
  CreateSymbolSpecFeeUsdJpy();

  // Create SYMBOLSPEC_ETH_XBT
  static exchange::core::common::CoreSymbolSpecification
  CreateSymbolSpecEthXbt();

  // Create SYMBOLSPECFEE_XBT_LTC
  static exchange::core::common::CoreSymbolSpecification
  CreateSymbolSpecFeeXbtLtc();

  static int32_t GetCurrency(const std::string &currency);
};

} // namespace util
} // namespace tests
} // namespace core2
} // namespace exchange
